### ISSUE TITLE
filter.Words not working while calling noteStore.findNotesMetadata() in c#

### ISSUE THREAD

**Issue by ItsDummy** [evernote/evernote-sdk-ruby#26]
NoteFilter filter = new NoteFilter();
filter.Words = "dummy";
NotesMetadataResultSpec spec = new NotesMetadataResultSpec();
spec.IncludeTitle = true;
NotesMetadataList notesList = noteStore.findNotesMetadata(api.AccessToken, filter, 0, pageSize, spec);

But not working.
Please do needfull.

I'm using source code from below repository

https://github.com/evernote/evernote-sdk-csharp/tree/master/src
https://github.com/apache/thrift

**Comment by ItsDummy** [comment]
For now I'm getting all notes of logged in user without filtering notes by word. Which is wrong.
I'm expecting get notes by filter word instead of getting all.

I'm filtering it by title temporarily.

            NoteFilter filter = new NoteFilter();
            filter.Ascending = false;
            //filter.Words = word; //* Not Filtering
            NotesMetadataResultSpec spec = new NotesMetadataResultSpec();
            spec.IncludeTitle = true;
            NotesMetadataList notesList = noteStore.findNotesMetadata(api.AccessToken, filter, 0, pageSize, spec);
            var notes = notesList.Notes.FindAll(x => x.Title.ToLower().Contains(word.ToLower()));

**Comment by iafan** [comment]
Before filtering by Title, try to do a query and print out the `notesList` object properties (`totalNotes`, `stoppedWords`, etc.) when doing a search with or without specifying `filter.Words` to see if there's any difference. Then go to Evernote Web, run the same word query in quotes, e.g. `"dummy"`, to match that exact word, and see how many results are returned by the service.

It's quite possible that a particular word that you're trying this on is a stop word, so it is ignored.

**Comment by ItsDummy** [comment]
Hi iafan,
Thanks for reply!

I'm using api of **sandbox.evernote.com** for development purpose.
 
If I use
filter.Words = "dummy";
In notesList object
TotalNotes = 0,
StoppedWords = null,
SearchedWords = null,
Notes = 0 (count)

_I go to Evernote Web YES It's working but on Sandbox Evernote Web It's not working_.
Is there any issue with Sandbox api for c#.

**It's my temporary alternate solution for now to get all notes and filter by title.** :0

**Comment by iafan** [comment]
> on Sandbox Evernote Web It's not working

Sandbox server is a separate server where you create a separate account with test notes. If you can't find notes by a certain keyword in the Web UI of your sandbox server, maybe you're trying to search for notes that are not there in the first place? In a nutshell, your search for `dummy` in Evernote Web on sandbox should return the same results as your search for `dummy*` using the API call. If they both fail to find notes, check the set of notes that you have in your sandbox.

**Comment by ItsDummy** [comment]
Yes I've already created separate account on sandbox Evernote and some sample notes also.
Dummy keyword is just an example even I can not search by any other keywords.

One month ago I've replaced my code with updated api of sandbox from below repository
https://github.com/evernote/evernote-sdk-csharp/tree/master/src
https://github.com/apache/thrift

Before api update it was searching notes by any keywords but after new api updates some methods deprecated by Evernote and suggests to use noteStore new methods.

**Comment by iafan** [comment]
I would still like to know if/how Evernote Web on sandbox behaves differently from direct API requests. Because the way I understood your comments above is that searching in Evernote Web (in the web client) doesn't yield proper results for you either. Clarifying this would help us isolate and reproduce the issue.

**Comment by ItsDummy** [comment]
![allNotes](https://user-images.githubusercontent.com/51440748/59085928-da3d0600-891d-11e9-8d1b-b57159658c17.PNG)
![NotSearching](https://user-images.githubusercontent.com/51440748/59085934-df9a5080-891d-11e9-9be2-a800d0caf63f.PNG)

Please find the attached.
Notes are already there in place. Still not searching by keyword.

**Comment by ItsDummy** [comment]
I have created note "dummy" on sandbox.evernote.com
![image](https://user-images.githubusercontent.com/51440748/59087329-fc388780-8921-11e9-8c3f-3b67496f1a72.png)

Tried to search using dummy (without quotes) yield no result
![image](https://user-images.githubusercontent.com/51440748/59087453-41f55000-8922-11e9-8716-21d356ea6682.png)

Tried to search using "dummy" (with quotes) yield no result 
![image](https://user-images.githubusercontent.com/51440748/59087486-5cc7c480-8922-11e9-9cab-c61eec687332.png)

**Comment by iafan** [comment]
Thanks for the additional feedback. It seems there's nothing wrong with the API or the way you use it, but there's something going on with note indexing on sandbox (that's why search doesn't work for you both in the web UI and via the API). I was able to reproduce the issue, and will file an internal ticket. Since this is not related to Evernote SDK or API, I suggest we close this ticket.

**Comment by ItsDummy** [comment]
Thanks for your quick responses.

How do i come to know, issue (as you have mentioned it is indexing issue on Sandbox) is fixed for my account?

Once it is done, surely we can close this ticket.

**Comment by iafan** [comment]
You will know the issue is fixed if search is working in the web client. I.e. in your example above, search by `dummy` will start returning notes. I can't give any ETA on when we will have this fixed, though, but give it at least a few days.

**Comment by ItsDummy** [comment]
Thanks a lot for all your help :). Appreciate your quick replies!

**Comment by sdcdsvsdv423** [comment]
Hello @iafan, 
is there any progress? Search in sandbox web version still does not work.
